// @generated drizzle-zero signature:sha256:d0dabe5f305bc5690db98008f6e1c076d96d4f210ec11101833e55160db5c8bd
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { CustomType } from "drizzle-zero";
import type * as drizzleSchema from "./schema";

const boardsTable = {
  name: "boards",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const cardsTable = {
  name: "cards",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    boardId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "board_id",
    },
    lane: {
      type: "string",
      optional: false,
      customType: null as unknown as CustomType<
        typeof drizzleSchema,
        "cards",
        "lane"
      >,
    },
    position: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    title: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const boardsRelationships = {
  cards: [
    {
      sourceField: ["id"],
      destField: ["boardId"],
      destSchema: "cards",
      cardinality: "many",
    },
  ],
} as const;
const cardsRelationships = {
  board: [
    {
      sourceField: ["boardId"],
      destField: ["id"],
      destSchema: "boards",
      cardinality: "one",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    boards: boardsTable,
    cards: cardsTable,
  },
  relationships: {
    boards: boardsRelationships,
    cards: cardsRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "boards" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Board = Row<(typeof schema)["tables"]["boards"]>;
/**
 * Represents a row from the "cards" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Card = Row<(typeof schema)["tables"]["cards"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
